### ISSUE TITLE
Error calculating gamma

### ISSUE THREAD

**Issue by MelnikovIG** [kipgparker/BackPropNetwork#2]
https://github.com/kipgparker/BackPropNetwork/blob/dab6ef1f89e9ee52cbc376e51d4c3887b428bead/BackpropNeuralNetwork/Assets/NeuralNetwork.cs#L237

Possible error here, it should be `gamma[i][j] += gamma[i + 1][k] * weights[i][k][j];` ?

**Comment by kipgparker** [comment]
Hey, sorry I have not been active on the repo at all, I think your right actually.
I will just check this over tomorrow and then push the changes.
Thank you for spotting this
